### ISSUE TITLE
Address remaining warning and notes from devtools::check()

### ISSUE THREAD

**Issue by jacobbien** [gregfaletto/cssr#3]
If you run `devtools::check()`, you'll see that there are some remaining issues to address.

- `formCssDesign` documentation is not finished (you probably know this...)
- In `getCssPreds`, a variable `newX` is used but not defined as an argument.  I'm guessing it is supposed to be `testX`?  But I figured it'd be best for you to fix this.

**Comment by gregfaletto** [comment]
Fixed the two above issues.
